<a href="https://colab.research.google.com/github/Ch-varshitha/Pandas/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pandas is used for data manipulation,data cleaning,data changing,reading and writing data files
 and data analysis.data analysis refers to extracting meaningful data from the raw data.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pd.DataFrame({
  "A":[10,20,30,40,50],
  "B":['a','b','c','d','e'],
  "C":np.random.randint(1,5)
})

    A  B  C
0  10  a  2
1  20  b  2
2  30  c  2
3  40  d  2
4  50  e  2

In [ ]:
pd.DataFrame(
    np.random.randint(0,9,(10,4)),columns=["A","B","C","D"]
)

   A  B  C  D
0  4  4  2  6
1  4  6  1  2
2  5  2  5  1
3  7  3  0  3
4  2  8  7  5
5  5  4  6  5
6  2  5  0  7
7  5  2  0  1
8  3  5  4  3
9  0  0  8  1

In [ ]:
np.random.rand(10,3).round(2)

array([[0.9 , 0.  , 0.78],
       [0.8 , 0.85, 0.58],
       [0.74, 0.51, 0.94],
       [0.58, 0.46, 0.54],
       [0.35, 0.31, 0.17],
       [0.35, 0.61, 0.66],
       [0.47, 0.46, 0.79],
       [0.16, 0.92, 0.16],
       [0.55, 0.02, 0.56],
       [0.16, 0.85, 0.44]])

In [ ]:
dfx=pd.DataFrame(
    np.random.randint(0,9,(10,4)),columns=["A","B","C","D"]
)

In [ ]:
dfx.to_excel("abcd.xlsx")

In [ ]:
pd.read_excel("abcd.xlsx")

   Unnamed: 0  A  B  C  D
0           0  1  5  3  4
1           1  1  8  7  6
2           2  3  0  3  2
3           3  1  6  5  6
4           4  5  5  1  6
5           5  1  0  4  2
6           6  4  7  6  3
7           7  0  7  0  0
8           8  5  1  7  3
9           9  7  7  5  4

In [ ]:
df=pd.DataFrame(
    np.random.rand(10,3).round(2),columns=["AA","BB","CC"]
)

In [ ]:
df.to_excel("varshi.xlsx")

In [ ]:
pd.read_excel("varshi.xlsx")

   Unnamed: 0     a     b     c
0           0  0.04  0.28  0.48
1           1  0.18  0.70  0.03
2           2  0.31  0.63  0.07
3           3  0.64  0.98  0.70
4           4  0.31  0.72  0.81
5           5  0.76  0.22  0.58
6           6  0.82  0.61  0.91
7           7  0.41  0.03  0.43
8           8  0.33  0.34  0.95
9           9  0.58  0.58  0.75

In [ ]:
df['d']=np.random.randint(1,9)

In [ ]:
df.describe(include="all")

               a          b         c     d
count  10.000000  10.000000  10.00000  10.0
mean    0.438000   0.509000   0.57100   7.0
std     0.254025   0.284154   0.32254   0.0
min     0.040000   0.030000   0.03000   7.0
25%     0.310000   0.295000   0.44250   7.0
50%     0.370000   0.595000   0.64000   7.0
75%     0.625000   0.682500   0.79500   7.0
max     0.820000   0.980000   0.95000   7.0

In [ ]:
 df.drop('AA',axis=1)

     BB    CC
0  0.42  0.77
1  0.04  0.18
2  0.16  0.23
3  0.95  0.74
4  0.39  0.86
5  0.98  0.89
6  0.42  0.87
7  0.16  0.73
8  0.73  0.92
9  0.79  0.27

In [ ]:
df['AA']=df['CC'].apply(lambda x:'big' if x>0.5 else 'small')

In [ ]:
df

      AA    BB    CC
0    big  0.42  0.77
1  small  0.04  0.18
2  small  0.16  0.23
3    big  0.95  0.74
4    big  0.39  0.86
5    big  0.98  0.89
6    big  0.42  0.87
7    big  0.16  0.73
8    big  0.73  0.92
9  small  0.79  0.27

In [ ]:
df.to_excel("ch.xlsx")